apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-app-config
data:
  DB_HOST: "{{ .Values.appConfig.dbHost }}"
  DB_NAME: "{{ .Values.appConfig.dbName }}"
  PORT: "{{ .Values.appConfig.port }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql-configmap
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS images (
        id INT AUTO_INCREMENT PRIMARY KEY,
        url VARCHAR(255) NOT NULL
    );
    INSERT INTO images (url) VALUES
    ('https://tenor.com/view/ryan-gosling-ryan-gosling-drive-flip-gif-5480671772097000575'),
    ('https://tenor.com/view/gosling-blade-runner-gosling-angry-gosling-pokerface-pokerface-gif-3757061166121710535'),
    ('https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExNWQ3bWZwbWJpZ3VrcmNrM3g0eTRvaWNtZjJrcmswZ3lhMTA3dGwxYiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/aoTKz5O4dE27S/giphy.gif');
