apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-app-config
data:
  DB_HOST: "{{ .Values.appConfig.dbHost }}"
  DB_NAME: "{{ .Values.appConfig.dbName }}"
  PORT: "{{ .Values.appConfig.port }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql-configmap
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS images (
        id INT AUTO_INCREMENT PRIMARY KEY,
        url VARCHAR(255) NOT NULL
    );
    INSERT INTO images (url) VALUES
    ('https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExZTEwdjA3enFrMnJvZnk0a2VrbDZnMGN2Z3FmanMwOHR0ZmxreTNmMSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/pMaPGoGE6LvS8/giphy.gif'),
    ('https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExc3Ixb25kcGtqam1jdmh5NzZiZmNwYzQ0bjRxZGp0ajBzbmV2NTI3eCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3o6EhJzC2UQLRMT2zm/giphy.gif'),
    ('https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExNWQ3bWZwbWJpZ3VrcmNrM3g0eTRvaWNtZjJrcmswZ3lhMTA3dGwxYiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/aoTKz5O4dE27S/giphy.gif');
