apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-app-config
data:
  DB_HOST: "{{ .Values.appConfig.dbHost }}"
  DB_NAME: "{{ .Values.appConfig.dbName }}"
  PORT: "{{ .Values.appConfig.port }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql-configmap
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS images (
        id INT AUTO_INCREMENT PRIMARY KEY,
        url VARCHAR(255) NOT NULL
    );
    INSERT INTO images (url) VALUES
    ('https://i.pinimg.com/originals/29/2a/50/292a50994d357e1884373ee8bf362562.gif'),
    ('https://i.pinimg.com/originals/2f/e4/67/2fe467f5a4350854f383c2185f1da571.gif'),
    ('https://media.tenor.com/iY7tFslwb0YAAAAe/ryan-gosling-confused-gif.png');